name: Residents
version: '${project.version}'
main: dev.aangepast.residents.Main
api-version: 1.19
depend: [Citizens]
commands:
  resident:
    permission: residents.admin
    permission-message: "You cannot execute this command."
    usage: /<command>
